#!/bin/sh
export PREFIX=/opt/trinity
export SYSCONFDIR=/etc/trinity
export LIBDIR=/opt/trinity/lib
export MANDIR=/opt/trinity/man
export QTDIR=/opt/trinity/tqt3
export PATH=/opt/trinity/tqt3/bin:/opt/trinity/bin:$PATH
export LD_LIBRARY_PATH=/opt/trinity/lib:/opt/trinity/lib/trinity:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=:/opt/trinity/lib/pkgconfig:/opt/trinity/tqt3/lib/pkgconfig:$PKG_CONFIG_PATH
# Enable only one of the following:
# export DEBUG_AUTOTOOL_OPT="--enable-debug=full"
#export DEBUG_AUTOTOOL_OPT="--disable-debug"
export DEBUG_AUTOTOOL_OPT=""
export DEBUG_CMAKE_OPT=""
export SVN_LIBRARY_DIR=/usr/lib
